name: Debug: check if node_modules exist on cache hit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-packages-

      - name: Install and cache NPM and Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: debug
        run: |
          ls
